### ISSUE TITLE
Empty (length = 0) TAG_List can't be read

### ISSUE THREAD

**Issue by PierreSchwang** [EngineHub/lin-bus#14]
When attempting to read an empty list using `LinCompoundTag#getListTag` as shown by NBTExplorer: 

![Image](https://github.com/user-attachments/assets/bbefc948-9263-454f-84d1-7c56ac4e920f)

an `java.lang.IllegalStateException: Tag under 'BlockEntities' exists, but is a END list instead of a COMPOUND list` is thrown.

As outlined by [wiki.vg/NBT](https://wiki.vg/NBT):
>  If the length of the list is 0 or negative, the type may be 0 (TAG_End) but otherwise it must be any other type

The method should return an empty LinListTag in that case (though the typing is not possible - it may be possible to specify `LinTagType.endTag()` in this particular case)

**Comment by octylFractal** [comment]
If you need to handle different potential list types, I think `getTag` works better here so that you're explicit about mapping it. I want to keep this library as close to the raw data as possible.
